# Generated by Django 3.2 on 2023-01-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('test_name', models.CharField(max_length=250)),
                ('survey_link', models.URLField()),
                ('result', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
