# Generated by Django 3.2 on 2023-01-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentsurvey',
            old_name='result',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='talentsurvey',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='talentsurvey',
            name='survey_link',
        ),
    ]
