# Generated by Django 3.2 on 2023-01-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('description', models.TextField(blank=True, null=True)),
                ('statistics', models.TextField(blank=True, null=True)),
                ('roadmap', models.ImageField(blank=True, null=True, upload_to='image/skills/roadmaps')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('address', models.URLField(blank=True, null=True)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='skills.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
