# Generated by Django 3.2 on 2023-07-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='phone_number',
        ),
    ]
