# Generated by Django 3.2 on 2023-07-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('user', '0007_user_is_consultant'),
        ('ticket', '0003_auto_20230706_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('answer', models.TextField()),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='consultation.consultant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('question', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('name', models.CharField(choices=[('html', 'اچ تی ام ال'), ('css', 'سی اس اس'), ('javascript', 'جاوا اسکریپت'), ('typescript', 'تایپ اسکریپت'), ('frontend', 'فرانت اند'), ('python', 'پایتون'), ('backend', 'بک اند'), ('ai', 'هوش مصنوعی'), ('nlp', 'ان ال پی')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tickettag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tickettag',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='skill_level',
            field=models.CharField(choices=[('1', 'آشنا نیستم'), ('2', 'تا حدودی آشنایی دارم'), ('3', 'کاملا آشنا هستم')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'درحال بررسی'), ('2', 'پاسخ داده شده'), ('3', 'اتمام مکالمه')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='QA',
        ),
        migrations.DeleteModel(
            name='TicketTag',
        ),
        migrations.AddField(
            model_name='tag',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='question',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='user.user'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='ticket.ticket'),
        ),
    ]
