# Generated by Django 3.2 on 2023-07-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_consultant'),
        ('ticket', '0004_auto_20230708_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_way',
            field=models.CharField(blank=True, choices=[('1', 'مشاوره تلفنی'), ('2', 'پیامک'), ('3', 'ایمیل')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='user.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('1', 'آشنا نیستم'), ('2', 'تا حدودی آشنایی دارم'), ('3', 'کاملا آشنا هستم')], max_length=1, null=True),
        ),
    ]
