# Generated by Django 3.2 on 2023-07-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20230710_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('اچ تی ام ال', 'اچ تی ام ال'), ('سی اس اس', 'سی اس اس'), ('جاوا اسکریپت', 'جاوا اسکریپت'), ('تایپ اسکریپت', 'تایپ اسکریپت'), ('فرانت اند', 'فرانت اند'), ('پایتون', 'پایتون'), ('بک اند', 'بک اند'), ('هوش مصنوعی', 'هوش مصنوعی'), ('ان ال پی', 'ان ال پی')], max_length=50),
        ),
    ]
