# Generated by Django 3.2 on 2023-01-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=250)),
                ('institute', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/certificate/%Y/%d/%m/')),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('avatar', models.ImageField(blank=True, upload_to='image/cv/avatar')),
                ('about_me', models.TextField()),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('character', models.CharField(blank=True, choices=[('1', 'منزوی'), ('2', 'دارای روحیه تیمی'), ('3', 'متمایل به ارتباط'), ('4', 'نداشتن تمایل به ارتباط')], max_length=100)),
                ('duty_system', models.CharField(choices=[('1', 'معافیت تحصیلی'), ('2', 'معافیت'), ('3', 'مشمول'), ('4', 'پایان خدمت')], max_length=1)),
                ('martial_status', models.CharField(choices=[('1', 'متاهل'), ('2', 'مجرد'), ('3', 'تمایل به اعلام ندارم')], max_length=1)),
                ('data_of_birth', models.DateField()),
                ('city', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True)),
                ('suggested_salary', models.BigIntegerField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/cv/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('industry', models.CharField(max_length=250)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('until_now', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('cv_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='cv.cv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('skill', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('cv_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.cv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('cv_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv.cv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('cv_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cv.cv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('cv_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.cv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('grade', models.CharField(max_length=250)),
                ('field_of_study', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('until_now', models.BooleanField(default=False)),
                ('cv_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.cv')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
