# Generated by Django 3.2 on 2023-01-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20230201_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='title',
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='industry',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
