# Generated by Django 3.2 on 2023-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20230201_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/files/certificate/%Y/%d/%m/'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/cv/avatar'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/files/cv/%Y/%m/%d/'),
        ),
    ]
